# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0008_auto_20170528_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='imagesapp.Image'),
        ),
    ]
